In [13]:
import numpy as np
import pcl
import cv2
import os
import math
from collections import  Counter

def load_pcd(loadpath='/home/wuhang/sofa.pcd'):
    cloud = pcl.load(loadpath)
    print('Loaded ' + loadpath)
    cloud_np = np.zeros([cloud.size,3])
    for i in range (0,cloud.size):
        cloud_np[i][0] = cloud[i][0]
        cloud_np[i][1] = cloud[i][1]
        cloud_np[i][2] = cloud[i][2]

    cloud_x = cloud_np[:,0]
    cloud_y = cloud_np[:,1]
    cloud_z = cloud_np[:,2]

    x_min = np.min(cloud_x)-((2.2-(np.max(cloud_x)-np.min(cloud_x)))/2)
    y_min = np.min(cloud_y)-((2.2-(np.max(cloud_y)-np.min(cloud_y)))/2)
    z_min = np.min(cloud_z)

    cloud_mod = cloud_np-np.hstack(( x_min*(np.ones([cloud.size,1])),
                                    y_min*(np.ones([cloud.size,1])),
                                    z_min*(np.ones([cloud.size,1])) ))
    return cloud_mod

In [43]:
cl = load_pcd('/home/wuhang/3d_vision/trash/res.pcd')
print np.shape(cl)
cl = np.round(cl, decimals=3)
cl2= np.unique(cl,axis=0)
print np.shape(cl2)

Loaded /home/wuhang/3d_vision/trash/res.pcd
(2225, 3)
(2225, 3)


In [39]:
print cl

[[0.1 0.7 0.6]
 [0.1 0.8 0.6]
 [0.2 0.7 0.6]
 ...
 [1.8 1.5 0.7]
 [1.9 1.5 0.6]
 [1.8 1.5 0.7]]
